version: "3.0"

services:
  genie:
    image: genie-builder:v1
    build:
      context: .
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      NODE_URL: "https://www.doitnow-man.com"
    stdin_open: true
    tty: true
    platform: linux/amd64
