[package]
name = "genie_account"
version = "1.0.0"

[dependencies]
AptosFramework = { local = "../framework/aptos-framework" }
MoveStdlib = { local = "../framework/move-stdlib"}
AptosStdlib = {local = "../framework/aptos-stdlib"}
AptosToken = { local = "../framework/aptos-token" }

[addresses]
std = "0x1"
aptos_framework = "0x1"
genie_account = "1336e5ba01edfa98c99dc091dcd5dd8f0ca353f01d1a60b690500ed17163345a"
